'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('products', [
      // Pet Gallery Products
      {
        petshop_id: 1,
        name: 'Royal Canin Kitten 2kg',
        description: 'Makanan kucing kitten dengan nutrisi lengkap',
        category: 'Makanan Kucing',
        brand: 'Royal Canin',
        price: 245000,
        stock: 15,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Royal+Canin+Kitten',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        petshop_id: 1,
        name: 'Pasir Kucing Bentonite 10L',
        description: 'Pasir kucing berkualitas tinggi yang dapat disapu',
        category: 'Pasir Kucing',
        brand: 'PetSafe',
        price: 85000,
        stock: 25,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Pasir+Kucing',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        petshop_id: 1,
        name: 'Vitamin Kucing Kompleks',
        description: 'Vitamin lengkap untuk kesehatan kucing',
        category: 'Vitamin & Suplemen',
        brand: 'PetVit',
        price: 55000,
        stock: 30,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Vitamin+Kucing',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        petshop_id: 1,
        name: 'Kandang Kucing 3 Tingkat',
        description: 'Kandang kucing multi-level dengan banyak ruang bermain',
        category: 'Kandang & Rumah',
        brand: 'Catify',
        price: 890000,
        stock: 3,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Kandang+Kucing',
        created_at: new Date(),
        updated_at: new Date(),
      },

      // Petshop Sejahtera Products
      {
        petshop_id: 2,
        name: 'Royal Canin Kitten 2kg',
        description: 'Makanan kucing kitten dengan nutrisi lengkap',
        category: 'Makanan Kucing',
        brand: 'Royal Canin',
        price: 250000,
        stock: 20,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Royal+Canin+Kitten',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        petshop_id: 2,
        name: 'Pro Plan Adult Dog 2.5kg',
        description: 'Makanan anjing dewasa dengan protein tinggi',
        category: 'Makanan Anjing',
        brand: 'Pro Plan',
        price: 180000,
        stock: 18,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Pro+Plan+Dog',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        petshop_id: 2,
        name: 'Mainan Kucing Bola Loncatan',
        description: 'Mainan interaktif untuk kucing yang aktif',
        category: 'Aksesoris & Mainan',
        brand: 'PetToy',
        price: 35000,
        stock: 50,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Mainan+Kucing',
        created_at: new Date(),
        updated_at: new Date(),
      },

      // Pet Paradise Products
      {
        petshop_id: 3,
        name: 'Royal Canin Kitten 2kg',
        description: 'Makanan kucing kitten dengan nutrisi lengkap',
        category: 'Makanan Kucing',
        brand: 'Royal Canin',
        price: 240000,
        stock: 25,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Royal+Canin+Kitten',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        petshop_id: 3,
        name: 'Shampo Anjing Professional Grade',
        description: 'Shampo grooming berkualitas tinggi untuk semua jenis anjing',
        category: 'Grooming',
        brand: 'GroomPro',
        price: 125000,
        stock: 12,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Shampo+Anjing',
        created_at: new Date(),
        updated_at: new Date(),
      },

      // Paws & Love Products
      {
        petshop_id: 4,
        name: 'Pro Plan Adult Dog 2.5kg',
        description: 'Makanan anjing dewasa dengan protein tinggi',
        category: 'Makanan Anjing',
        brand: 'Pro Plan',
        price: 175000,
        stock: 22,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Pro+Plan+Dog',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        petshop_id: 4,
        name: 'Kalung Anjing Nylon',
        description: 'Kalung anjing nyaman dengan berbagai warna',
        category: 'Aksesoris & Mainan',
        brand: 'PetWear',
        price: 45000,
        stock: 40,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Kalung+Anjing',
        created_at: new Date(),
        updated_at: new Date(),
      },

      // Furry Friends Products
      {
        petshop_id: 5,
        name: 'Royal Canin Kitten 2kg',
        description: 'Makanan kucing kitten dengan nutrisi lengkap',
        category: 'Makanan Kucing',
        brand: 'Royal Canin',
        price: 255000,
        stock: 10,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Royal+Canin+Kitten',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        petshop_id: 5,
        name: 'Pro Plan Adult Dog 2.5kg',
        description: 'Makanan anjing dewasa dengan protein tinggi',
        category: 'Makanan Anjing',
        brand: 'Pro Plan',
        price: 185000,
        stock: 28,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Pro+Plan+Dog',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        petshop_id: 5,
        name: 'Kandang Khusus Hamster',
        description: 'Kandang lengkap dengan aksesoris untuk hamster',
        category: 'Kandang & Rumah',
        brand: 'HamsterHome',
        price: 250000,
        stock: 5,
        is_available: true,
        image_url: 'https://via.placeholder.com/200x200?text=Kandang+Hamster',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('products', null, {});
  },
};
